config:
  EMR_CLUSTER_NAME: "my-hail-02-cluster" # Give a name to your EMR cluster
  EC2_NAME_TAG: "my-hail-EMR" # Adds a tag to the individual EC2 instances
  OWNER_TAG: "emr-owner" # EC2 owner tag
  PROJECT_TAG: "my-project" # Project tag
  REGION: "us-east-1"
  MASTER_INSTANCE_TYPE: "m4.large"
  WORKER_INSTANCE_TYPE: "r4.4xlarge"
  WORKER_COUNT: 2 # Number of worker nodes
  WORKER_BID_PRICE: "0.44" # Required for spot instances
  MASTER_HD_SIZE: "50" # Size in GB - For large data sets, more HD space may be required
  WORKER_HD_SIZE: "150" # Size in GB - For large data sets, more HD space may be required
  SUBNET_ID: "" # This field can be either left blank or for further security you can specify your private subnet ID in the form: subnet-1a2b3c4d
  S3_URI: "s3://my-s3-bucket/my/path/" # URI of S3 bucket and path for EMR log storage
  KEY_NAME: "/path/to/my-key.pem" # Fully-qualified path to PEM key to use, including file suffix
  WORKER_SECURITY_GROUP: "" # ID of security group to use. If empty creates a new group by default. 
  MASTER_SECURITY_GROUP: "" # ID of security group to use. If empty creates a new group by default.
  HAIL_VERSION: "current" # Specify a git hash version (the first 7-12 characters will suffice) to install a specific commit/version. When left empty or "current" will install the latest version of Hail available in the repo
  EMR_RELEASE_LABEL: "emr-5.23.0" # EMR version
  BOOTSTRAP_ACTIONS: "s3://hms-dbmi-docs/hail_bootstrap/bootstrap_python36.sh" # Bootstrap actions script.  Note default tries to install python36, which will fail